name: Bump version
on:
  push:
    branches: ["prod"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
      - name: Publish package
        run: pub publish -f
      - name: set up env var
          run: echo "VERSION=$(git tag --sort=-refname | awk 'match($0, /^v[0-9]+.*$/)' | head -n 1)" >> $GITHUB_ENV
      - name: set up env var
          run: echo "NEW=$(IN=${{ env.VERSION }}
               F1=`echo $IN | cut -f1 '-d.'`
               F2=`echo $IN | cut -f2 '-d.'`
               F3=`echo $IN | cut -f3 '-d.'`
               F3=$(( F3 + 1 ))
               if [ "$F3" -gt 99 ] ; then F3=00 ; F2=$(( F2 + 1 )) ; fi
               if [ "$F2" -gt 99 ] ; then F2=00 ; F1=$(( F1 + 1 )) ; fi
               OUT="$F1.$F2.$F3"
               echo $OUT)" >> $GITHUB_ENV
      - name: create tag
          reun: git tag ${{ env.NEW }}
      - name: push tag
          reun: git push --tag
